"""add user_ai_configs table

Revision ID: 05982e7ca5fc
Revises: 
Create Date: 2026-03-18 14:27:11.642400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05982e7ca5fc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('text_provider', sa.String(length=64), nullable=True),
    sa.Column('text_api_key', sa.Text(), nullable=True),
    sa.Column('text_endpoint', sa.Text(), nullable=True),
    sa.Column('text_model', sa.String(length=128), nullable=True),
    sa.Column('vision_provider', sa.String(length=64), nullable=True),
    sa.Column('vision_api_key', sa.Text(), nullable=True),
    sa.Column('vision_endpoint', sa.Text(), nullable=True),
    sa.Column('vision_model', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_ai_configs')
    # ### end Alembic commands ###
