"""add daily_sentences table

Revision ID: 2682493d3797
Revises: 95211421c454
Create Date: 2026-03-18 22:15:54.583593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2682493d3797'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_sentences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('translation', sa.Text(), nullable=False),
    sa.Column('grammar_point', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_sentences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_sentences_date'), ['date'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_sentences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_sentences_date'))

    op.drop_table('daily_sentences')
    # ### end Alembic commands ###
