"""add wechat_openid to users

Revision ID: 95211421c454
Revises: 05982e7ca5fc
Create Date: 2026-03-18 18:03:55.253019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95211421c454'
down_revision = '05982e7ca5fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wechat_openid', sa.String(length=64), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_wechat_openid'), ['wechat_openid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wechat_openid'))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('wechat_openid')

    # ### end Alembic commands ###
