"""add image_url to analysis_tasks

Revision ID: d39f45f051f8
Revises: f6e406b7579d
Create Date: 2026-03-21 20:58:06.482470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd39f45f051f8'
down_revision = 'f6e406b7579d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=2048), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
