"""add analysis_tasks table

Revision ID: eef5801c799e
Revises: 2682493d3797
Create Date: 2026-03-21 12:26:57.386090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eef5801c799e'
down_revision = '2682493d3797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sentence_id', sa.String(length=36), nullable=True),
    sa.Column('sentence_content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_tasks_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('sync_idempotency_records', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_idempotency_user_device_op', ['user_id', 'device_id', 'op_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.drop_index(batch_op.f('ix_users_wechat_openid'))
        batch_op.create_index(batch_op.f('ix_users_wechat_openid'), ['wechat_openid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wechat_openid'))
        batch_op.create_index(batch_op.f('ix_users_wechat_openid'), ['wechat_openid'], unique=False)
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)

    with op.batch_alter_table('sync_idempotency_records', schema=None) as batch_op:
        batch_op.drop_constraint('uq_idempotency_user_device_op', type_='unique')

    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_status'))

    op.drop_table('analysis_tasks')
    # ### end Alembic commands ###
