"""add task_type and ocr fields to analysis_tasks

Revision ID: f6e406b7579d
Revises: eef5801c799e
Create Date: 2026-03-21 19:25:29.886850

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.mysql import MEDIUMTEXT


# revision identifiers, used by Alembic.
revision = 'f6e406b7579d'
down_revision = 'eef5801c799e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_type', sa.String(length=20), nullable=True, server_default='analysis'))
        batch_op.add_column(sa.Column('image_data', sa.Text().with_variant(MEDIUMTEXT(), 'mysql'), nullable=True))
        batch_op.add_column(sa.Column('image_mime', sa.String(length=50), nullable=True))
        batch_op.alter_column('sentence_content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_analysis_tasks_task_type'), ['task_type'], unique=False)

    # Backfill existing rows
    op.execute("UPDATE analysis_tasks SET task_type = 'analysis' WHERE task_type IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analysis_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_tasks_task_type'))
        batch_op.alter_column('sentence_content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('image_mime')
        batch_op.drop_column('image_data')
        batch_op.drop_column('task_type')

    # ### end Alembic commands ###
